sudo: required
servives:
  - docker


before_install:
  - docker build -t mlgthemoja/finapp-test -f ./client/Dockerfile.dev ./client


script:
  - docker run mlgthemoja/finapp-test yarn test -- --coverage

after_success:
  - docker build -t mlgthemoja/finapp-client ./client
  - docker build -t mlgthemoja/finapp-nginx ./nginx
  - docker build -t mlgthemoja/finapp-server ./server
  - docker build -t mlgthemoja/finapp-worker ./worker

  # Log in to the docker cli aka hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the built images and push them to docker hub
  - docker push mlgthemoja/finapp-nginx
  - docker push mlgthemoja/finapp-client
  - docker push mlgthemoja/finapp-server
  - docker push mlgthemoja/finapp-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: finapp-multidocker
  env: FinappMultidocker-env
  bucket_name: elasticbeanstalk-us-east-2-341448331141
  bucket_path: finapp-multidocker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY